'use client';
import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import {
  X, ArrowLeft, ArrowRight, Check, Paperclip, Mail, MessageSquare, RotateCcw, Pencil,
  Palmtree, Stethoscope, Repeat,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { useCurrentUser } from '@/lib/session';
import {
  useBalance,
  useMyLeaves,
  useSubmitLeave,
  useUsers,
  type Balance,
} from '@/lib/hooks';
import { computeDurationDays } from '@/lib/leave';
import { Button } from '../ui/Button';
import { Field, TextArea, TextInput } from '../ui/Field';
import { cx, fmtDate, leaveTypeLabel } from '../../lib/utils';
import type { LeaveType, NotificationChannel, HalfDaySlot } from '../../lib/types';
import './LeaveApplicationFlow.css';

interface Props {
  open: boolean;
  onClose: () => void;
}

type Step = 1 | 2 | 3 | 4 | 5 | 6;
const STEP_LABELS = ['Type', 'Dates', 'Details', 'Send', 'Review'];

export function LeaveApplicationFlow({ open, onClose }: Props) {
  const user = useCurrentUser();
  const { data: balance } = useBalance();
  const { data: myLeaves = [] } = useMyLeaves();
  const { data: allUsers = [] } = useUsers();
  const submit = useSubmitLeave();

  const admins = useMemo(
    () => allUsers.filter((u) => u.role === 'HR' || u.role === 'ADMIN'),
    [allUsers]
  );

  const activeReqs = useMemo(
    () => myLeaves.filter((r) => r.status === 'PENDING' || r.status === 'APPROVED'),
    [myLeaves]
  );

  const [step, setStep] = useState<Step>(1);
  const [leaveType, setLeaveType] = useState<LeaveType | null>(null);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [isHalfDay, setIsHalfDay] = useState(false);
  const [halfDaySlot, setHalfDaySlot] = useState<HalfDaySlot>('MORNING');
  const [useTimeRange, setUseTimeRange] = useState(false);
  const [timeFrom, setTimeFrom] = useState('09:00');
  const [timeTo, setTimeTo] = useState('13:00');
  const [reason, setReason] = useState('');
  const [description, setDescription] = useState('');
  const [attachment, setAttachment] = useState<File | null>(null);
  const [channels, setChannels] = useState<NotificationChannel[]>(['EMAIL']);
  const [customMessage, setCustomMessage] = useState<string | null>(null);
  const [editingMessage, setEditingMessage] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const singleDay = !!startDate && (!endDate || endDate === startDate);

  const duration = useMemo(() => {
    if (!startDate || !leaveType) return 0;
    const end = endDate || startDate;
    return computeDurationDays({
      leaveType,
      startDate,
      endDate: end,
      isHalfDay,
      halfDaySlot: isHalfDay ? halfDaySlot : undefined,
      timeFrom: useTimeRange && singleDay && !isHalfDay ? timeFrom : undefined,
      timeTo: useTimeRange && singleDay && !isHalfDay ? timeTo : undefined,
      reason: reason || 'x',
      channels: channels.length ? channels : ['EMAIL'],
    });
  }, [startDate, endDate, isHalfDay, halfDaySlot, useTimeRange, timeFrom, timeTo, singleDay, leaveType, reason, channels]);

  const availableBalance = useMemo(() => {
    if (!leaveType || !balance) return 0;
    if (leaveType === 'CASUAL')
      return balance.casualTotal - balance.casualUsed - balance.casualPending;
    if (leaveType === 'SICK')
      return balance.sickTotal - balance.sickUsed - balance.sickPending;
    return balance.replacementBalance;
  }, [leaveType, balance]);

  const dateOverlap = useMemo(() => {
    if (!startDate) return null;
    const end = endDate || startDate;
    return activeReqs.find((r) => !(end < r.startDate || startDate > r.endDate)) ?? null;
  }, [startDate, endDate, activeReqs]);

  function reset() {
    setStep(1);
    setLeaveType(null);
    setStartDate('');
    setEndDate('');
    setIsHalfDay(false);
    setHalfDaySlot('MORNING');
    setUseTimeRange(false);
    setTimeFrom('09:00');
    setTimeTo('13:00');
    setReason('');
    setDescription('');
    setAttachment(null);
    setChannels(['EMAIL']);
    setCustomMessage(null);
    setEditingMessage(false);
    setDone(false);
    setError(null);
  }

  function handleClose() {
    onClose();
    setTimeout(reset, 400);
  }

  function autoGeneratedMessage(): string {
    if (!user || !leaveType) return '';
    const startFmt = startDate ? fmtDate(startDate) : '[start]';
    const endFmt = endDate ? fmtDate(endDate) : startFmt;
    const durLabel = useTimeRange && singleDay
      ? `${timeFrom}–${timeTo}`
      : duration === 0.5
      ? 'a half day'
      : `${duration} working day${duration === 1 ? '' : 's'}`;
    return `Dear HR & Leadership,

I am writing to formally request ${leaveTypeLabel(leaveType).toLowerCase()} from ${startFmt} to ${endFmt} (${durLabel}).

Reason: ${reason || '[your reason]'}${description ? `\n\n${description}` : ''}
${attachment ? '\nPlease find the supporting document attached.\n' : ''}
I have ensured that my responsibilities will be covered during this period. I kindly request your approval at your earliest convenience.

Thank you for your consideration.

Regards,
${user.fullName}
${user.employeeIdCode || ''} · ${user.department || ''}`;
  }

  const displayMessage = customMessage ?? autoGeneratedMessage();

  function toggleChannel(c: NotificationChannel) {
    setChannels((cs) => (cs.includes(c) ? cs.filter((x) => x !== c) : [...cs, c]));
  }

  function canProceed(): boolean {
    if (step === 1) return !!leaveType && availableBalance > 0;
    if (step === 2) {
      if (!startDate) return false;
      const end = endDate || startDate;
      if (end < startDate) return false;
      if (dateOverlap) return false;
      if (duration <= 0) return false;
      if (duration > availableBalance) return false;
      return true;
    }
    if (step === 3) return reason.trim().length > 0;
    if (step === 4) return channels.length > 0;
    return true;
  }

  function handleSubmit() {
    if (!user || !leaveType) return;
    setError(null);
    submit.mutate(
      {
        leaveType,
        startDate,
        endDate: endDate || startDate,
        isHalfDay,
        halfDaySlot: isHalfDay ? halfDaySlot : undefined,
        timeFrom: useTimeRange && singleDay && !isHalfDay ? timeFrom : undefined,
        timeTo: useTimeRange && singleDay && !isHalfDay ? timeTo : undefined,
        reason,
        description: description || undefined,
        channels,
        customMessage: customMessage ?? undefined,
      },
      {
        onSuccess: () => setDone(true),
        onError: (e: Error) => setError(e.message),
      }
    );
  }

  if (!open) return null;
  if (!user || !balance) return null;

  return (
    <AnimatePresence>
      {open && (
        <>
          <motion.div
            className="laf-overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            onClick={handleClose}
          />
          <div className="laf-wrap" onClick={handleClose}>
            <motion.div
              className="laf"
              onClick={(e) => e.stopPropagation()}
              initial={{ opacity: 0, y: 16, scale: 0.98 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 16, scale: 0.98 }}
              transition={{ duration: 0.28, ease: 'easeOut' }}
              role="dialog"
              aria-modal="true"
            >
              <header className="laf-header">
                <div>
                  <h2>Apply for Leave</h2>
                  <p>Fill out a few quick details — you can review everything before sending.</p>
                </div>
                <button className="laf-close" onClick={handleClose} aria-label="Close">
                  <X size={20} />
                </button>
              </header>

              {!done && (
                <div className="laf-steps">
                  {STEP_LABELS.map((label, i) => {
                    const idx = (i + 1) as Step;
                    const active = step === idx;
                    const complete = step > idx;
                    return (
                      <div key={label} className={cx('laf-step', active && 'laf-step-active', complete && 'laf-step-complete')}>
                        <span className="laf-step-circle">
                          {complete ? <Check size={12} /> : idx}
                        </span>
                        <span className="laf-step-label">{label}</span>
                      </div>
                    );
                  })}
                </div>
              )}

              <div className="laf-body">
                {done ? (
                  <SuccessState onClose={handleClose} />
                ) : (
                  <AnimatePresence mode="wait">
                    <motion.div
                      key={step}
                      initial={{ opacity: 0, x: 24 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: -24 }}
                      transition={{ duration: 0.22 }}
                    >
                      {step === 1 && (
                        <StepType balance={balance} leaveType={leaveType} onChoose={setLeaveType} />
                      )}
                      {step === 2 && (
                        <StepDates
                          startDate={startDate}
                          endDate={endDate}
                          setStartDate={setStartDate}
                          setEndDate={setEndDate}
                          isHalfDay={isHalfDay}
                          setIsHalfDay={setIsHalfDay}
                          halfDaySlot={halfDaySlot}
                          setHalfDaySlot={setHalfDaySlot}
                          useTimeRange={useTimeRange}
                          setUseTimeRange={setUseTimeRange}
                          timeFrom={timeFrom}
                          setTimeFrom={setTimeFrom}
                          timeTo={timeTo}
                          setTimeTo={setTimeTo}
                          duration={duration}
                          available={availableBalance}
                          overlap={dateOverlap}
                        />
                      )}
                      {step === 3 && (
                        <StepDetails
                          reason={reason}
                          setReason={setReason}
                          description={description}
                          setDescription={setDescription}
                          attachment={attachment}
                          setAttachment={setAttachment}
                        />
                      )}
                      {step === 4 && (
                        <StepSend
                          channels={channels}
                          toggle={toggleChannel}
                          adminNames={admins.map((a) => `${a.fullName} (${a.designation || a.role})`)}
                          adminEmails={admins.map((a) => a.email)}
                        />
                      )}
                      {step === 5 && (
                        <StepReview
                          messageText={displayMessage}
                          isEdited={customMessage !== null}
                          editing={editingMessage}
                          setEditing={setEditingMessage}
                          onEditChange={setCustomMessage}
                          onReset={() => {
                            setCustomMessage(null);
                            setEditingMessage(false);
                          }}
                          channels={channels}
                          error={error}
                        />
                      )}
                    </motion.div>
                  </AnimatePresence>
                )}
              </div>

              {!done && (
                <footer className="laf-footer">
                  {step > 1 ? (
                    <Button
                      variant="ghost"
                      leadingIcon={<ArrowLeft size={16} />}
                      onClick={() => setStep((step - 1) as Step)}
                    >
                      Back
                    </Button>
                  ) : (
                    <span />
                  )}
                  {step < 5 ? (
                    <Button
                      variant="primary"
                      trailingIcon={<ArrowRight size={16} />}
                      disabled={!canProceed()}
                      onClick={() => setStep((step + 1) as Step)}
                    >
                      Continue
                    </Button>
                  ) : (
                    <Button
                      variant="primary"
                      size="md"
                      loading={submit.isPending}
                      onClick={handleSubmit}
                    >
                      Submit Leave Request
                    </Button>
                  )}
                </footer>
              )}
            </motion.div>
          </div>
        </>
      )}
    </AnimatePresence>
  );
}

/* ─── Sub-Steps ─── */

function StepType({
  balance,
  leaveType,
  onChoose,
}: {
  balance: Balance;
  leaveType: LeaveType | null;
  onChoose: (t: LeaveType) => void;
}) {
  const cards: { t: LeaveType; title: string; left: number; color: string; bg: string; Icon: LucideIcon }[] = [
    {
      t: 'CASUAL',
      title: 'Casual Leave',
      left: balance.casualTotal - balance.casualUsed - balance.casualPending,
      color: 'var(--color-leave-casual)',
      bg: 'var(--color-leave-casual-light)',
      Icon: Palmtree,
    },
    {
      t: 'SICK',
      title: 'Sick Leave',
      left: balance.sickTotal - balance.sickUsed - balance.sickPending,
      color: 'var(--color-leave-sick)',
      bg: 'var(--color-leave-sick-light)',
      Icon: Stethoscope,
    },
    {
      t: 'REPLACEMENT',
      title: 'Replacement',
      left: balance.replacementBalance,
      color: 'var(--color-leave-replacement)',
      bg: 'var(--color-leave-replacement-light)',
      Icon: Repeat,
    },
  ];

  return (
    <div>
      <h3 className="laf-step-title">What kind of leave is this?</h3>
      <p className="laf-step-desc">Pick a type — your available balance is shown on each card.</p>
      <div className="laf-typegrid">
        {cards.map((c) => {
          const disabled = c.left <= 0;
          const active = leaveType === c.t;
          return (
            <button
              key={c.t}
              className={cx('laf-typecard', active && 'laf-typecard-active', disabled && 'laf-typecard-disabled')}
              disabled={disabled}
              onClick={() => onChoose(c.t)}
              style={{ '--tc-color': c.color, '--tc-bg': c.bg } as React.CSSProperties}
            >
              <div className="laf-typecard-icon"><c.Icon size={28} strokeWidth={1.6} /></div>
              <div className="laf-typecard-title">{c.title}</div>
              <div className="laf-typecard-left">
                {disabled ? 'No days remaining' : `${c.left} day${c.left === 1 ? '' : 's'} left`}
              </div>
              {active && <div className="laf-typecard-check"><Check size={14} /></div>}
            </button>
          );
        })}
      </div>
    </div>
  );
}

function StepDates({
  startDate, endDate, setStartDate, setEndDate,
  isHalfDay, setIsHalfDay,
  halfDaySlot, setHalfDaySlot,
  useTimeRange, setUseTimeRange,
  timeFrom, setTimeFrom, timeTo, setTimeTo,
  duration, available, overlap,
}: {
  startDate: string; endDate: string;
  setStartDate: (s: string) => void; setEndDate: (s: string) => void;
  isHalfDay: boolean; setIsHalfDay: (b: boolean) => void;
  halfDaySlot: HalfDaySlot; setHalfDaySlot: (s: HalfDaySlot) => void;
  useTimeRange: boolean; setUseTimeRange: (b: boolean) => void;
  timeFrom: string; setTimeFrom: (s: string) => void;
  timeTo: string; setTimeTo: (s: string) => void;
  duration: number; available: number;
  overlap: { status: string } | null;
}) {
  const canGranularSingle = startDate && (!endDate || startDate === endDate);
  const durationErr =
    duration > available ? `That's more than your remaining balance of ${available} day${available === 1 ? '' : 's'}.` : undefined;

  return (
    <div>
      <h3 className="laf-step-title">When are you taking leave?</h3>
      <p className="laf-step-desc">Weekends don't count. Single day? You can also request a half-day or a specific time slot.</p>
      <div className="laf-daterow">
        <Field label="Start date" required>
          <TextInput
            type="date"
            value={startDate}
            onChange={(e) => {
              setStartDate(e.target.value);
              if (endDate && endDate < e.target.value) setEndDate(e.target.value);
            }}
          />
        </Field>
        <Field label="End date" required>
          <TextInput
            type="date"
            value={endDate || startDate}
            min={startDate}
            disabled={isHalfDay || useTimeRange}
            onChange={(e) => setEndDate(e.target.value)}
          />
        </Field>
      </div>

      {canGranularSingle && (
        <div className="laf-halfday">
          <label className="laf-check">
            <input
              type="checkbox"
              checked={isHalfDay}
              onChange={(e) => {
                setIsHalfDay(e.target.checked);
                if (e.target.checked) {
                  setEndDate(startDate);
                  setUseTimeRange(false);
                }
              }}
            />
            Half day
          </label>
          {isHalfDay && (
            <div className="laf-halfslot">
              {(['MORNING', 'AFTERNOON'] as HalfDaySlot[]).map((s) => (
                <button
                  key={s}
                  className={cx('laf-slot', halfDaySlot === s && 'laf-slot-active')}
                  onClick={() => setHalfDaySlot(s)}
                >
                  {s === 'MORNING' ? '🌅 Morning' : '🌇 Afternoon'}
                </button>
              ))}
            </div>
          )}

          <label className="laf-check" style={{ marginTop: 10 }}>
            <input
              type="checkbox"
              checked={useTimeRange}
              disabled={isHalfDay}
              onChange={(e) => {
                setUseTimeRange(e.target.checked);
                if (e.target.checked) {
                  setEndDate(startDate);
                  setIsHalfDay(false);
                }
              }}
            />
            Specific time slot within the day
          </label>
          {useTimeRange && (
            <div className="laf-timerow">
              <Field label="From">
                <TextInput type="time" value={timeFrom} onChange={(e) => setTimeFrom(e.target.value)} />
              </Field>
              <Field label="To">
                <TextInput type="time" value={timeTo} onChange={(e) => setTimeTo(e.target.value)} />
              </Field>
            </div>
          )}
        </div>
      )}

      <div className="laf-duration">
        <div>
          <div className="laf-duration-label">Duration</div>
          <div className="laf-duration-value">
            {duration > 0
              ? `${duration} working day${duration === 1 ? '' : 's'}`
              : '—'}
          </div>
        </div>
        <div>
          <div className="laf-duration-label">After approval you'll have</div>
          <div className="laf-duration-value">
            {Math.max(0, available - duration)} day{available - duration === 1 ? '' : 's'} left
          </div>
        </div>
      </div>

      {overlap && (
        <div className="laf-inline-error">
          You already have a {overlap.status.toLowerCase()} leave request that overlaps this range.
        </div>
      )}
      {durationErr && <div className="laf-inline-error">{durationErr}</div>}
    </div>
  );
}

function StepDetails({
  reason, setReason, description, setDescription, attachment, setAttachment,
}: {
  reason: string; setReason: (s: string) => void;
  description: string; setDescription: (s: string) => void;
  attachment: File | null; setAttachment: (f: File | null) => void;
}) {
  return (
    <div>
      <h3 className="laf-step-title">Tell us why</h3>
      <p className="laf-step-desc">A short reason helps your manager review quickly.</p>
      <Field label="Reason / title" required hint={`${reason.length} / 100`}>
        <TextInput
          maxLength={100}
          value={reason}
          onChange={(e) => setReason(e.target.value)}
          placeholder="e.g. Sister's wedding"
        />
      </Field>
      <div style={{ height: 12 }} />
      <Field label="Description (optional)" hint={`${description.length} / 500`}>
        <TextArea
          maxLength={500}
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Provide additional context if needed"
        />
      </Field>
      <div style={{ height: 12 }} />
      <div>
        <div className="field-label" style={{ marginBottom: 6 }}>Attach a document (optional)</div>
        <label className="laf-file">
          <input
            type="file"
            accept=".pdf,.jpg,.jpeg,.png"
            onChange={(e) => setAttachment(e.target.files?.[0] ?? null)}
          />
          <span className="laf-file-btn">
            <Paperclip size={14} />
            {attachment ? attachment.name : 'Choose a file (.pdf, .jpg, .png · max 5MB)'}
          </span>
          {attachment && (
            <button
              type="button"
              className="laf-file-remove"
              onClick={(e) => {
                e.preventDefault();
                setAttachment(null);
              }}
            >
              Remove
            </button>
          )}
        </label>
      </div>
    </div>
  );
}

function StepSend({
  channels, toggle,
}: {
  channels: NotificationChannel[];
  toggle: (c: NotificationChannel) => void;
  adminNames: string[]; adminEmails: string[];
}) {
  return (
    <div>
      <h3 className="laf-step-title">How should we send it?</h3>
      <p className="laf-step-desc">Choose one or both. Email is on by default.</p>
      <div className="laf-channels">
        <ChannelBox
          active={channels.includes('EMAIL')}
          onClick={() => toggle('EMAIL')}
          icon={<Mail size={20} />}
          label="Email"
          desc="Sent to HR"
        />
        <ChannelBox
          active={channels.includes('IN_APP')}
          onClick={() => toggle('IN_APP')}
          icon={<MessageSquare size={20} />}
          label="In-app message"
          desc="Delivered inside HRIS instantly"
        />
      </div>
      {channels.length === 0 && (
        <div className="laf-inline-error" style={{ marginTop: 12 }}>
          Select at least one channel.
        </div>
      )}
    </div>
  );
}

function ChannelBox({ active, onClick, icon, label, desc }: {
  active: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
  desc: string;
}) {
  return (
    <button
      type="button"
      className={cx('laf-channel', active && 'laf-channel-active')}
      onClick={onClick}
    >
      <span className="laf-channel-icon">{icon}</span>
      <div className="laf-channel-body">
        <div className="laf-channel-label">{label}</div>
        <div className="laf-channel-desc">{desc}</div>
      </div>
      <span className={cx('laf-channel-check', active && 'laf-channel-check-active')}>
        {active && <Check size={12} />}
      </span>
    </button>
  );
}

function StepReview({
  messageText, isEdited, editing, setEditing, onEditChange, onReset, channels, error,
}: {
  messageText: string; isEdited: boolean;
  editing: boolean; setEditing: (b: boolean) => void;
  onEditChange: (s: string) => void; onReset: () => void;
  channels: NotificationChannel[];
  error?: string | null;
}) {
  return (
    <div>
      <h3 className="laf-step-title">Review your message</h3>
      <p className="laf-step-desc">This is the exact message that will be sent. You can edit it below.</p>
      <div className="laf-preview">
        <div className="laf-preview-head">
          <div className="laf-preview-tabs">
            {channels.includes('EMAIL') && <span className="laf-preview-tab">📧 Email</span>}
            {channels.includes('IN_APP') && <span className="laf-preview-tab">💬 In-app</span>}
          </div>
          <div className="laf-preview-actions">
            {isEdited && (
              <button className="laf-linkbtn" onClick={onReset}>
                <RotateCcw size={12} /> Reset to default
              </button>
            )}
            {!editing && (
              <button className="laf-linkbtn" onClick={() => setEditing(true)}>
                <Pencil size={12} /> Edit
              </button>
            )}
          </div>
        </div>
        {editing ? (
          <TextArea
            className="laf-preview-editor"
            value={messageText}
            onChange={(e) => onEditChange(e.target.value)}
            rows={16}
          />
        ) : (
          <pre className="laf-preview-body">{messageText}</pre>
        )}
      </div>
      {error && <div className="laf-inline-error" style={{ marginTop: 12 }}>{error}</div>}
    </div>
  );
}

function SuccessState({ onClose }: { onClose: () => void }) {
  return (
    <motion.div
      className="laf-success"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
    >
      <svg viewBox="0 0 64 64" width="80" height="80" className="laf-success-check">
        <circle cx="32" cy="32" r="30" fill="var(--color-success-light)" />
        <motion.path
          d="M20 33 L29 42 L45 24"
          fill="none"
          stroke="var(--color-success)"
          strokeWidth="4"
          strokeLinecap="round"
          strokeLinejoin="round"
          initial={{ pathLength: 0 }}
          animate={{ pathLength: 1 }}
          transition={{ duration: 0.6, ease: 'easeOut', delay: 0.15 }}
        />
      </svg>
      <h3>Your leave request has been submitted!</h3>
      <p>You'll be notified as soon as it's reviewed.</p>
      <div className="laf-success-actions">
        <Button variant="primary" onClick={onClose}>Back to dashboard</Button>
      </div>
    </motion.div>
  );
}
